package modulo_compras;

import control.ControlFlujo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;

/**
 *
 * @author PC WHITE WOLF
 */
public class HistorialCompras extends javax.swing.JPanel {
    
    private static HistorialCompras instance;
    
    /**
     * Creates new form SubmenuCompras
     */
    private HistorialCompras() {initComponents();}
    
    public static HistorialCompras getInstance(){
        if(instance == null)
            instance = new HistorialCompras();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTítuloCompras = new javax.swing.JLabel();
        btnHistorialReposiciones = new javax.swing.JLabel();
        btnHistorialNuevosProductos = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        IconoHistorialNuevosProductos = new javax.swing.JLabel();
        IconoHistorialReposiciones = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLTítuloCompras.setBackground(new java.awt.Color(255, 255, 255));
        jLTítuloCompras.setFont(new java.awt.Font("Century Gothic", 1, 72)); // NOI18N
        jLTítuloCompras.setForeground(new java.awt.Color(0, 0, 0));
        jLTítuloCompras.setText("Compras");

        btnHistorialReposiciones.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorialReposiciones.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnHistorialReposiciones.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorialReposiciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHistorialReposiciones.setText("Reposiciones");
        btnHistorialReposiciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialReposiciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistorialReposiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialReposicionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialReposicionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialReposicionesMouseExited(evt);
            }
        });

        btnHistorialNuevosProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorialNuevosProductos.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnHistorialNuevosProductos.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorialNuevosProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHistorialNuevosProductos.setText("Nuevos Productos");
        btnHistorialNuevosProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialNuevosProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistorialNuevosProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialNuevosProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialNuevosProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialNuevosProductosMouseExited(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        IconoHistorialNuevosProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoHistorialNuevosProductos.png"))); // NOI18N

        IconoHistorialReposiciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoHistorialReposiciones.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jLTítuloCompras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IconoHistorialReposiciones)
                            .addComponent(IconoHistorialNuevosProductos))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHistorialReposiciones)
                            .addComponent(btnHistorialNuevosProductos))))
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTítuloCompras)
                        .addGap(98, 98, 98)
                        .addComponent(btnHistorialNuevosProductos)
                        .addGap(133, 133, 133)
                        .addComponent(btnHistorialReposiciones)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 159, Short.MAX_VALUE)
                        .addComponent(IconoHistorialNuevosProductos)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(IconoHistorialReposiciones)
                                .addGap(215, 215, 215))))))
        );

        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistorialReposicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialReposicionesMouseClicked
        ControlFlujo.mostrarHistorialComprasReposiciones();
    }//GEN-LAST:event_btnHistorialReposicionesMouseClicked

    private void btnHistorialReposicionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialReposicionesMouseEntered
        btnHistorialReposiciones.setForeground(Color.red);
    }//GEN-LAST:event_btnHistorialReposicionesMouseEntered

    private void btnHistorialReposicionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialReposicionesMouseExited
        btnHistorialReposiciones.setForeground(Color.black);
    }//GEN-LAST:event_btnHistorialReposicionesMouseExited

    private void btnHistorialNuevosProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialNuevosProductosMouseClicked
        ControlFlujo.mostrarHistorialComprasNuevosProductos();
    }//GEN-LAST:event_btnHistorialNuevosProductosMouseClicked

    private void btnHistorialNuevosProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialNuevosProductosMouseEntered
        btnHistorialNuevosProductos.setForeground(Color.red);
    }//GEN-LAST:event_btnHistorialNuevosProductosMouseEntered

    private void btnHistorialNuevosProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialNuevosProductosMouseExited
        btnHistorialNuevosProductos.setForeground(Color.black);
    }//GEN-LAST:event_btnHistorialNuevosProductosMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlFlujo.mostrarSubmenuCompras();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoHistorialNuevosProductos;
    private javax.swing.JLabel IconoHistorialReposiciones;
    private javax.swing.JLabel btnHistorialNuevosProductos;
    private javax.swing.JLabel btnHistorialReposiciones;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLTítuloCompras;
    // End of variables declaration//GEN-END:variables
}