package modulo_compras;

import control.ControlFlujo;
import control.ControlOperaciones;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author PC WHITE WOLF
 */
public class NuevoProducto extends javax.swing.JPanel {
    
    private static NuevoProducto instance;
    
    private boolean nombreValido;
    private boolean colorValido;
    private boolean tipoValido;
    private boolean precioUnitarioValido;
    private boolean precioVentaValido;
    private boolean categoriaValida;
    private boolean cajaValida;
    private boolean XSValido;
    private boolean SValido;
    private boolean MValido;
    private boolean LValido;
    private boolean XLValido;
    /**
     * Constructor por defecto.
     */
    private NuevoProducto() {
        initComponents();
        btnConfirmarCompra.setEnabled(false);
        jTFTallaXSInput.setText("0");
        jTFTallaSInput.setText("0");
        jTFTallaMInput.setText("0");
        jTFTallaLInput.setText("0");
        jTFTallaXLInput.setText("0");
        
        ControlOperaciones.limiteCaracteres(jTFNombre, 100);
        ControlOperaciones.limiteCaracteres(jTFColor, 50);
        ControlOperaciones.limiteCaracteres(jTFProveedor, 100);
        ControlOperaciones.limiteCaracteres(jTFTipoPrenda, 50);
        ControlOperaciones.limiteCaracteres(jTFPrecioCompraUnitario, 20);
        ControlOperaciones.limiteCaracteres(jTFPrecioVentaSugerido, 20);
        ControlOperaciones.limiteCaracteres(jTFTallaXSInput, 5);
        ControlOperaciones.limiteCaracteres(jTFTallaSInput, 5);
        ControlOperaciones.limiteCaracteres(jTFTallaMInput, 5);
        ControlOperaciones.limiteCaracteres(jTFTallaLInput, 5);
        ControlOperaciones.limiteCaracteres(jTFTallaXLInput, 5);
        
        ControlOperaciones.configurarCamposTexto(jTFNombre);
        ControlOperaciones.configurarCamposTexto(jTFColor);
        ControlOperaciones.configurarCamposTexto(jTFTipoPrenda);
        ControlOperaciones.configurarCamposTexto(jTFProveedor);
        
        ControlOperaciones.configurarCamposPrecios(jTFPrecioCompraUnitario);
        ControlOperaciones.configurarCamposPrecios(jTFPrecioVentaSugerido);
        
        ControlOperaciones.configurarCamposCantidades(jTFTallaXSInput);
        ControlOperaciones.configurarCamposCantidades(jTFTallaSInput);
        ControlOperaciones.configurarCamposCantidades(jTFTallaMInput);
        ControlOperaciones.configurarCamposCantidades(jTFTallaLInput);
        ControlOperaciones.configurarCamposCantidades(jTFTallaXLInput);
        
        validacionDinamica(jTFNombre);
        validacionDinamica(jTFColor);
        validacionDinamica(jTFTipoPrenda);
        validacionDinamica(jTFPrecioCompraUnitario);
        validacionDinamica(jTFPrecioVentaSugerido);
        validacionDinamica(jTFTallaXSInput);
        validacionDinamica(jTFTallaSInput);
        validacionDinamica(jTFTallaMInput);
        validacionDinamica(jTFTallaLInput);
        validacionDinamica(jTFTallaXLInput);
    }
    
    public static NuevoProducto getInstance(){
        if(instance == null)
            instance = new NuevoProducto();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTítuloNuevoProducto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jTFNombre = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jLCategoria = new javax.swing.JLabel();
        jTFPrecioCompraUnitario = new javax.swing.JTextField();
        jLPrecioCompraUnitario = new javax.swing.JLabel();
        jTFTipoPrenda = new javax.swing.JTextField();
        jLTipoPrenda = new javax.swing.JLabel();
        jLColor = new javax.swing.JLabel();
        jTFColor = new javax.swing.JTextField();
        jTFPrecioVentaSugerido = new javax.swing.JTextField();
        jLPrecioVentaSugerido = new javax.swing.JLabel();
        jLCajaAlmacenamiento = new javax.swing.JLabel();
        jCBCajaAlmacenamiento = new javax.swing.JComboBox<>();
        jTFProveedor = new javax.swing.JTextField();
        jLProveedor = new javax.swing.JLabel();
        jLTalla = new javax.swing.JLabel();
        jLTallaS = new javax.swing.JLabel();
        jLTallaXS1 = new javax.swing.JLabel();
        jLTallaM = new javax.swing.JLabel();
        jLTallaL = new javax.swing.JLabel();
        jLTallaXL = new javax.swing.JLabel();
        jTFTallaXSInput = new javax.swing.JTextField();
        jTFTallaSInput = new javax.swing.JTextField();
        jTFTallaMInput = new javax.swing.JTextField();
        jTFTallaLInput = new javax.swing.JTextField();
        jTFTallaXLInput = new javax.swing.JTextField();
        jLTalla1 = new javax.swing.JLabel();
        btnConfirmarCompra = new javax.swing.JButton();
        jCBCategoria = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLTítuloNuevoProducto.setBackground(new java.awt.Color(255, 255, 255));
        jLTítuloNuevoProducto.setFont(new java.awt.Font("Century Gothic", 1, 72)); // NOI18N
        jLTítuloNuevoProducto.setForeground(new java.awt.Color(0, 0, 0));
        jLTítuloNuevoProducto.setText("Nuevo Producto");

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jTFNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTFNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLNombre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLNombre.setText("Nombre del producto*:");

        jLCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jLCategoria.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jLCategoria.setText("Categoría del producto*:");

        jTFPrecioCompraUnitario.setBackground(new java.awt.Color(255, 255, 255));
        jTFPrecioCompraUnitario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFPrecioCompraUnitario.setForeground(new java.awt.Color(0, 0, 0));
        jTFPrecioCompraUnitario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLPrecioCompraUnitario.setBackground(new java.awt.Color(255, 255, 255));
        jLPrecioCompraUnitario.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLPrecioCompraUnitario.setForeground(new java.awt.Color(0, 0, 0));
        jLPrecioCompraUnitario.setText("Precio de compra unitario*:");

        jTFTipoPrenda.setBackground(new java.awt.Color(255, 255, 255));
        jTFTipoPrenda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFTipoPrenda.setForeground(new java.awt.Color(0, 0, 0));
        jTFTipoPrenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLTipoPrenda.setBackground(new java.awt.Color(255, 255, 255));
        jLTipoPrenda.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTipoPrenda.setForeground(new java.awt.Color(0, 0, 0));
        jLTipoPrenda.setText("Tipo de prenda*:");

        jLColor.setBackground(new java.awt.Color(255, 255, 255));
        jLColor.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLColor.setForeground(new java.awt.Color(0, 0, 0));
        jLColor.setText("Color del producto*:");

        jTFColor.setBackground(new java.awt.Color(255, 255, 255));
        jTFColor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFColor.setForeground(new java.awt.Color(0, 0, 0));
        jTFColor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTFPrecioVentaSugerido.setBackground(new java.awt.Color(255, 255, 255));
        jTFPrecioVentaSugerido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFPrecioVentaSugerido.setForeground(new java.awt.Color(0, 0, 0));
        jTFPrecioVentaSugerido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLPrecioVentaSugerido.setBackground(new java.awt.Color(255, 255, 255));
        jLPrecioVentaSugerido.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLPrecioVentaSugerido.setForeground(new java.awt.Color(0, 0, 0));
        jLPrecioVentaSugerido.setText("Precio de venta sugerido*:");

        jLCajaAlmacenamiento.setBackground(new java.awt.Color(255, 255, 255));
        jLCajaAlmacenamiento.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLCajaAlmacenamiento.setForeground(new java.awt.Color(0, 0, 0));
        jLCajaAlmacenamiento.setText("Caja de almacenamiento*:");

        jCBCajaAlmacenamiento.setBackground(new java.awt.Color(255, 255, 255));
        jCBCajaAlmacenamiento.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCBCajaAlmacenamiento.setForeground(new java.awt.Color(0, 0, 0));
        jCBCajaAlmacenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jCBCajaAlmacenamiento.setBorder(null);
        jCBCajaAlmacenamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCBCajaAlmacenamiento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCajaAlmacenamientoItemStateChanged(evt);
            }
        });

        jTFProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jTFProveedor.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jTFProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLProveedor.setBackground(new java.awt.Color(255, 255, 255));
        jLProveedor.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLProveedor.setForeground(new java.awt.Color(0, 0, 0));
        jLProveedor.setText("Proveedor (opcional):");

        jLTalla.setBackground(new java.awt.Color(255, 255, 255));
        jLTalla.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTalla.setForeground(new java.awt.Color(0, 0, 0));
        jLTalla.setText("Talla:");

        jLTallaS.setBackground(new java.awt.Color(255, 255, 255));
        jLTallaS.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTallaS.setForeground(new java.awt.Color(0, 0, 0));
        jLTallaS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTallaS.setText("S");
        jLTallaS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLTallaXS1.setBackground(new java.awt.Color(255, 255, 255));
        jLTallaXS1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTallaXS1.setForeground(new java.awt.Color(0, 0, 0));
        jLTallaXS1.setText("XS");

        jLTallaM.setBackground(new java.awt.Color(255, 255, 255));
        jLTallaM.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTallaM.setForeground(new java.awt.Color(0, 0, 0));
        jLTallaM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTallaM.setText("M");
        jLTallaM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLTallaL.setBackground(new java.awt.Color(255, 255, 255));
        jLTallaL.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTallaL.setForeground(new java.awt.Color(0, 0, 0));
        jLTallaL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTallaL.setText("L");
        jLTallaL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLTallaXL.setBackground(new java.awt.Color(255, 255, 255));
        jLTallaXL.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTallaXL.setForeground(new java.awt.Color(0, 0, 0));
        jLTallaXL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTallaXL.setText("XL");
        jLTallaXL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTFTallaXSInput.setBackground(new java.awt.Color(255, 255, 255));
        jTFTallaXSInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFTallaXSInput.setForeground(new java.awt.Color(0, 0, 0));
        jTFTallaXSInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFTallaXSInput.setText("0");
        jTFTallaXSInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFTallaXSInput.setMinimumSize(new java.awt.Dimension(64, 23));
        jTFTallaXSInput.setPreferredSize(new java.awt.Dimension(64, 23));

        jTFTallaSInput.setBackground(new java.awt.Color(255, 255, 255));
        jTFTallaSInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFTallaSInput.setForeground(new java.awt.Color(0, 0, 0));
        jTFTallaSInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFTallaSInput.setText("0");
        jTFTallaSInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFTallaSInput.setMinimumSize(new java.awt.Dimension(64, 23));
        jTFTallaSInput.setPreferredSize(new java.awt.Dimension(64, 23));

        jTFTallaMInput.setBackground(new java.awt.Color(255, 255, 255));
        jTFTallaMInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFTallaMInput.setForeground(new java.awt.Color(0, 0, 0));
        jTFTallaMInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFTallaMInput.setText("0");
        jTFTallaMInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFTallaMInput.setMinimumSize(new java.awt.Dimension(64, 23));
        jTFTallaMInput.setPreferredSize(new java.awt.Dimension(64, 23));

        jTFTallaLInput.setBackground(new java.awt.Color(255, 255, 255));
        jTFTallaLInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFTallaLInput.setForeground(new java.awt.Color(0, 0, 0));
        jTFTallaLInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFTallaLInput.setText("0");
        jTFTallaLInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFTallaLInput.setMinimumSize(new java.awt.Dimension(64, 23));
        jTFTallaLInput.setPreferredSize(new java.awt.Dimension(64, 23));

        jTFTallaXLInput.setBackground(new java.awt.Color(255, 255, 255));
        jTFTallaXLInput.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFTallaXLInput.setForeground(new java.awt.Color(0, 0, 0));
        jTFTallaXLInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFTallaXLInput.setText("0");
        jTFTallaXLInput.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFTallaXLInput.setMinimumSize(new java.awt.Dimension(64, 23));
        jTFTallaXLInput.setPreferredSize(new java.awt.Dimension(64, 23));

        jLTalla1.setBackground(new java.awt.Color(255, 255, 255));
        jLTalla1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLTalla1.setForeground(new java.awt.Color(0, 0, 0));
        jLTalla1.setText("Cantidad:");

        btnConfirmarCompra.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmarCompra.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnConfirmarCompra.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarCompra.setText("Confirmar compra");
        btnConfirmarCompra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnConfirmarCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarCompra.setFocusPainted(false);
        btnConfirmarCompra.setFocusable(false);
        btnConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCompraActionPerformed(evt);
            }
        });

        jCBCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jCBCategoria.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCBCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "DAMA", "CABALLERO" }));
        jCBCategoria.setBorder(null);
        jCBCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCBCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCategoriaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTítuloNuevoProducto)
                .addGap(306, 306, 306))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFPrecioCompraUnitario)
                            .addComponent(jLPrecioCompraUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFTipoPrenda)
                                    .addComponent(jLTipoPrenda, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCajaAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBCajaAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFColor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTFNombre)
                                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTFPrecioVentaSugerido)
                                    .addComponent(jLPrecioVentaSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLTalla)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLTalla1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFProveedor)
                                        .addComponent(jLProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTFTallaSInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLTallaS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLTallaXS1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLTallaM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLTallaL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLTallaXL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(57, 57, 57)
                                                    .addComponent(jTFTallaXSInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTFTallaMInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTFTallaLInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTFTallaXLInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                                .addComponent(btnConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTítuloNuevoProducto)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLPrecioVentaSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFPrecioVentaSugerido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTipoPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCajaAlmacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jCBCajaAlmacenamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFTipoPrenda, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLTallaXS1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTFTallaXSInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLTallaS, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTFTallaSInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLTallaM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFTallaMInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLColor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTallaL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFTallaLInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFColor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLTallaXL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTFTallaXLInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLPrecioCompraUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPrecioCompraUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlFlujo.mostrarSubmenuCompras();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarCompraActionPerformed
        
    }//GEN-LAST:event_btnConfirmarCompraActionPerformed

    private void jCBCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCategoriaItemStateChanged
        validarCampos();
    }//GEN-LAST:event_jCBCategoriaItemStateChanged

    private void jCBCajaAlmacenamientoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCajaAlmacenamientoItemStateChanged
        validarCampos();
    }//GEN-LAST:event_jCBCajaAlmacenamientoItemStateChanged

    private void validacionDinamica(JTextField campo){
        campo.getDocument().addDocumentListener( new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validarCampos();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validarCampos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validarCampos();
            }
        });
    }
    
    private void validarCampos(){
        nombreValido = ControlOperaciones.validarCampoInvalidoTexto(jTFNombre);
        colorValido = ControlOperaciones.validarCampoInvalidoTexto(jTFColor);
        tipoValido = ControlOperaciones.validarCampoInvalidoTexto(jTFTipoPrenda);
        precioUnitarioValido = ControlOperaciones.validarCampoInvalidoPrecios(jTFPrecioCompraUnitario);
        precioVentaValido = ControlOperaciones.validarCampoInvalidoPrecios(jTFPrecioVentaSugerido);
        categoriaValida = ControlOperaciones.validarCampoInvalidoComboBox(jCBCategoria);
        cajaValida = ControlOperaciones.validarCampoInvalidoComboBox(jCBCajaAlmacenamiento);
        XSValido = ControlOperaciones.validarCampoInvalidoTexto(jTFTallaXSInput);
        SValido = ControlOperaciones.validarCampoInvalidoTexto(jTFTallaSInput);
        MValido = ControlOperaciones.validarCampoInvalidoTexto(jTFTallaMInput);
        LValido = ControlOperaciones.validarCampoInvalidoTexto(jTFTallaLInput);
        XLValido = ControlOperaciones.validarCampoInvalidoTexto(jTFTallaXLInput);
        
        btnConfirmarCompra.setEnabled(
                nombreValido && colorValido && tipoValido 
                        && 
                precioUnitarioValido && precioVentaValido 
                        && 
                categoriaValida && cajaValida 
                        &&
                XSValido && SValido && MValido && LValido && XLValido
        );
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarCompra;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jCBCajaAlmacenamiento;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JLabel jLCajaAlmacenamiento;
    private javax.swing.JLabel jLCategoria;
    private javax.swing.JLabel jLColor;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLPrecioCompraUnitario;
    private javax.swing.JLabel jLPrecioVentaSugerido;
    private javax.swing.JLabel jLProveedor;
    private javax.swing.JLabel jLTalla;
    private javax.swing.JLabel jLTalla1;
    private javax.swing.JLabel jLTallaL;
    private javax.swing.JLabel jLTallaM;
    private javax.swing.JLabel jLTallaS;
    private javax.swing.JLabel jLTallaXL;
    private javax.swing.JLabel jLTallaXS1;
    private javax.swing.JLabel jLTipoPrenda;
    private javax.swing.JLabel jLTítuloNuevoProducto;
    private javax.swing.JTextField jTFColor;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTFPrecioCompraUnitario;
    private javax.swing.JTextField jTFPrecioVentaSugerido;
    private javax.swing.JTextField jTFProveedor;
    private javax.swing.JTextField jTFTallaLInput;
    private javax.swing.JTextField jTFTallaMInput;
    private javax.swing.JTextField jTFTallaSInput;
    private javax.swing.JTextField jTFTallaXLInput;
    private javax.swing.JTextField jTFTallaXSInput;
    private javax.swing.JTextField jTFTipoPrenda;
    // End of variables declaration//GEN-END:variables
}