package modulo_compras;

import control.ControlFlujo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;

/**
 *
 * @author PC WHITE WOLF
 */
public class SubmenuCompras extends javax.swing.JPanel {
    
    private static SubmenuCompras instance;
    
    /**
     * Creates new form SubmenuCompras
     */
    private SubmenuCompras() {initComponents();}
    
    public static SubmenuCompras getInstance(){
        if(instance == null)
            instance = new SubmenuCompras();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTítuloCompras = new javax.swing.JLabel();
        btnNuevoProducto = new javax.swing.JLabel();
        btnReposicion = new javax.swing.JLabel();
        btnHistorialCompras = new javax.swing.JLabel();
        IconoHistorialCompras = new javax.swing.JLabel();
        IconoReposicion = new javax.swing.JLabel();
        IconoReposicion1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLTítuloCompras.setBackground(new java.awt.Color(255, 255, 255));
        jLTítuloCompras.setFont(new java.awt.Font("Century Gothic", 1, 72)); // NOI18N
        jLTítuloCompras.setForeground(new java.awt.Color(0, 0, 0));
        jLTítuloCompras.setText("Compras");

        btnNuevoProducto.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevoProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevoProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoProductoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoProductoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNuevoProductoMouseExited(evt);
            }
        });

        btnReposicion.setBackground(new java.awt.Color(255, 255, 255));
        btnReposicion.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnReposicion.setForeground(new java.awt.Color(0, 0, 0));
        btnReposicion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReposicion.setText("Reposición");
        btnReposicion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReposicion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReposicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReposicionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReposicionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReposicionMouseExited(evt);
            }
        });

        btnHistorialCompras.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorialCompras.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnHistorialCompras.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorialCompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHistorialCompras.setText("Historial de compras");
        btnHistorialCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistorialCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialComprasMouseExited(evt);
            }
        });

        IconoHistorialCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoHistorialCompras.png"))); // NOI18N

        IconoReposicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoNuevoProducto.png"))); // NOI18N

        IconoReposicion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoReposicion.png"))); // NOI18N

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IconoHistorialCompras)
                            .addComponent(IconoReposicion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHistorialCompras)
                            .addComponent(btnReposicion)
                            .addComponent(jLTítuloCompras)
                            .addComponent(btnNuevoProducto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(329, 329, 329)
                    .addComponent(IconoReposicion1)
                    .addContainerGap(823, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTítuloCompras)
                .addGap(84, 84, 84)
                .addComponent(btnNuevoProducto)
                .addGap(82, 82, 82)
                .addComponent(btnReposicion)
                .addGap(93, 93, 93)
                .addComponent(btnHistorialCompras)
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(IconoReposicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconoHistorialCompras)
                .addGap(13, 13, 13)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(342, Short.MAX_VALUE)
                    .addComponent(IconoReposicion1)
                    .addGap(250, 250, 250)))
        );

        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoProductoMouseClicked

    }//GEN-LAST:event_btnNuevoProductoMouseClicked

    private void btnNuevoProductoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoProductoMouseEntered
        btnNuevoProducto.setForeground(Color.red);
    }//GEN-LAST:event_btnNuevoProductoMouseEntered

    private void btnNuevoProductoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoProductoMouseExited
        btnNuevoProducto.setForeground(Color.black);
    }//GEN-LAST:event_btnNuevoProductoMouseExited

    private void btnReposicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReposicionMouseClicked
        
    }//GEN-LAST:event_btnReposicionMouseClicked

    private void btnReposicionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReposicionMouseEntered
        btnReposicion.setForeground(Color.red);
    }//GEN-LAST:event_btnReposicionMouseEntered

    private void btnReposicionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReposicionMouseExited
        btnReposicion.setForeground(Color.black);
    }//GEN-LAST:event_btnReposicionMouseExited

    private void btnHistorialComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialComprasMouseClicked
        
    }//GEN-LAST:event_btnHistorialComprasMouseClicked

    private void btnHistorialComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialComprasMouseEntered
        btnHistorialCompras.setForeground(Color.red);
    }//GEN-LAST:event_btnHistorialComprasMouseEntered

    private void btnHistorialComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialComprasMouseExited
        btnHistorialCompras.setForeground(Color.black);
    }//GEN-LAST:event_btnHistorialComprasMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlFlujo.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoHistorialCompras;
    private javax.swing.JLabel IconoReposicion;
    private javax.swing.JLabel IconoReposicion1;
    private javax.swing.JLabel btnHistorialCompras;
    private javax.swing.JLabel btnNuevoProducto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel btnReposicion;
    private javax.swing.JLabel jLTítuloCompras;
    // End of variables declaration//GEN-END:variables
}