package moduloVentas;

import control.ControlFlujo;
import control.ControlOperaciones;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC WHITE WOLF
 */
public class AgregarProducto extends javax.swing.JPanel {
    
    private static AgregarProducto instance;
    
    private boolean campoValido;
    private boolean filtroValido;
    private final DefaultTableModel modeloTablaProductos;
    private final DefaultTableModel modeloTablaTallas;
    private final IngresarCantidad ingresarCantidad;
    /**
     * Constructor por defecto.
     */
    private AgregarProducto() {
        initComponents();
        btnIngresarCantidad.setVisible(false);
        jLBuscador.setVisible(false);
        jTFBuscador.setVisible(false);
        jLFiltroCategoria.setVisible(false);
        jCBCategoria.setVisible(false);
        
        modeloTablaProductos = (DefaultTableModel) jTProductos.getModel();
        modeloTablaProductos.setRowCount(0);
        jTProductos.setModel(modeloTablaProductos);
        
        modeloTablaTallas = (DefaultTableModel) jTallas1.getModel();
        modeloTablaTallas.setRowCount(0);
        jTallas1.setModel(modeloTablaTallas);
        
        ingresarCantidad = new IngresarCantidad((Frame) SwingUtilities.getWindowAncestor(this), true);
        ingresarCantidad.setLocationRelativeTo(this);
        
        ControlOperaciones.configurarCamposTexto(jTFBuscador);
    }
    
    public static AgregarProducto getInstance(){
        if(instance == null)
            instance = new AgregarProducto();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTítuloNuevoProducto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jTFBuscador = new javax.swing.JTextField();
        jLBuscador = new javax.swing.JLabel();
        jLFiltroCategoria = new javax.swing.JLabel();
        jCBFiltro = new javax.swing.JComboBox<>();
        btnIngresarCantidad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jCBCategoria = new javax.swing.JComboBox<>();
        jLFiltroBusqueda = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTallas1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLTítuloNuevoProducto.setBackground(new java.awt.Color(255, 255, 255));
        jLTítuloNuevoProducto.setFont(new java.awt.Font("Century Gothic", 1, 72)); // NOI18N
        jLTítuloNuevoProducto.setForeground(new java.awt.Color(0, 0, 0));
        jLTítuloNuevoProducto.setText("Agregar producto");

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jTFBuscador.setBackground(new java.awt.Color(255, 255, 255));
        jTFBuscador.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTFBuscador.setForeground(new java.awt.Color(0, 0, 0));
        jTFBuscador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTFBuscador.setMaximumSize(new java.awt.Dimension(64, 21));

        jLBuscador.setBackground(new java.awt.Color(255, 255, 255));
        jLBuscador.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLBuscador.setForeground(new java.awt.Color(0, 0, 0));
        jLBuscador.setText("Nombre del producto:");

        jLFiltroCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jLFiltroCategoria.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLFiltroCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jLFiltroCategoria.setText("Categoría:");

        jCBFiltro.setBackground(new java.awt.Color(255, 255, 255));
        jCBFiltro.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCBFiltro.setForeground(new java.awt.Color(0, 0, 0));
        jCBFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Nombre", "Tipo", "Categoría", "Color", "Talla" }));
        jCBFiltro.setBorder(null);
        jCBFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCBFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBFiltroItemStateChanged(evt);
            }
        });

        btnIngresarCantidad.setBackground(new java.awt.Color(0, 0, 0));
        btnIngresarCantidad.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnIngresarCantidad.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarCantidad.setText("Ingresar cantidad");
        btnIngresarCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnIngresarCantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarCantidad.setFocusPainted(false);
        btnIngresarCantidad.setFocusable(false);
        btnIngresarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCantidadActionPerformed(evt);
            }
        });

        jTProductos.setBackground(new java.awt.Color(255, 255, 255));
        jTProductos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTProductos.setForeground(new java.awt.Color(0, 0, 0));
        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo", "Categoría", "Color", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTProductos.setMaximumSize(new java.awt.Dimension(375, 0));
        jTProductos.setMinimumSize(new java.awt.Dimension(375, 0));
        jTProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTProductos.getTableHeader().setResizingAllowed(false);
        jTProductos.getTableHeader().setReorderingAllowed(false);
        jTProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTProductos);

        jCBCategoria.setBackground(new java.awt.Color(255, 255, 255));
        jCBCategoria.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCBCategoria.setForeground(new java.awt.Color(0, 0, 0));
        jCBCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAMA", "CABALLERO" }));
        jCBCategoria.setBorder(null);
        jCBCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCBCategoria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCategoriaItemStateChanged(evt);
            }
        });

        jLFiltroBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        jLFiltroBusqueda.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLFiltroBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        jLFiltroBusqueda.setText("Filtro de búsqueda:");

        jTallas1.setBackground(new java.awt.Color(255, 255, 255));
        jTallas1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTallas1.setForeground(new java.awt.Color(0, 0, 0));
        jTallas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talla", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTallas1.setMaximumSize(new java.awt.Dimension(375, 0));
        jTallas1.setMinimumSize(new java.awt.Dimension(375, 0));
        jTallas1.setPreferredSize(new java.awt.Dimension(375, 0));
        jTallas1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTallas1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTallas1.getTableHeader().setResizingAllowed(false);
        jTallas1.getTableHeader().setReorderingAllowed(false);
        jTallas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTallas1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTallas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFiltroBusqueda))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFiltroCategoria))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(256, 349, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnIngresarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTítuloNuevoProducto)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLTítuloNuevoProducto)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLFiltroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIngresarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLFiltroCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 20, 20);
                super.paint(g2, c);
                g2.dispose();
            }
        });
        btnIngresarCantidad.setBorderPainted(false);
        btnIngresarCantidad.setContentAreaFilled(false);
        btnIngresarCantidad.setOpaque(false);
        btnIngresarCantidad.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 10, 10);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        if(jLFiltroCategoria.isVisible())
            jLFiltroCategoria.setVisible(false);

        if(jCBCategoria.isVisible())
            jCBCategoria.setVisible(false);

        if(jLBuscador.isVisible())
            jLBuscador.setVisible(false);

        if(jTFBuscador.isVisible())
            jTFBuscador.setVisible(false);
        
        modeloTablaProductos.setRowCount(0);
        modeloTablaTallas.setRowCount(0);
        btnIngresarCantidad.setVisible(false);
        ControlFlujo.mostrarVender();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIngresarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCantidadActionPerformed
        
    }//GEN-LAST:event_btnIngresarCantidadActionPerformed
    
    private void mostrarIngresarCantidad(){
        ingresarCantidad.setVisible(true);
    }
    
    private void jCBFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBFiltroItemStateChanged
        if(ControlOperaciones.validarCampoInvalidoComboBox(jCBFiltro)){
            if(jCBFiltro.getSelectedItem().equals("Nombre")){
                filtrarBuscador("Nombre del producto");
                ControlOperaciones.limiteCaracteres(jTFBuscador, 100);
                activarBuscador();
                
            } else if(jCBFiltro.getSelectedItem().equals("Tipo")){
                filtrarBuscador("Tipo de producto");
                ControlOperaciones.limiteCaracteres(jTFBuscador, 50);
                activarBuscador();
                
            }else if(jCBFiltro.getSelectedItem().equals("Color")){
                filtrarBuscador("Color del producto");
                ControlOperaciones.limiteCaracteres(jTFBuscador, 50);
                activarBuscador();
                
            }else if(jCBFiltro.getSelectedItem().equals("Talla")){
                filtrarBuscador("Talla de producto");
                ControlOperaciones.limiteCaracteres(jTFBuscador, 5);
                activarBuscador();
                
            } else if(jCBFiltro.getSelectedItem().equals("Categoría")){
                if(jLBuscador.isVisible())
                    jLBuscador.setVisible(false);
                
                if(jTFBuscador.isVisible())
                    jTFBuscador.setVisible(false);
                
                if(!jLFiltroCategoria.isVisible())
                    jLFiltroCategoria.setVisible(true);

                if(!jCBCategoria.isVisible())
                    jCBCategoria.setVisible(true);
                
                modeloTablaProductos.setRowCount(0);
                modeloTablaTallas.setRowCount(0);
            }
        } else{
            if(jLFiltroCategoria.isVisible())
                jLFiltroCategoria.setVisible(false);

            if(jCBCategoria.isVisible())
                jCBCategoria.setVisible(false);

            if(jLBuscador.isVisible())
                jLBuscador.setVisible(false);

            if(jTFBuscador.isVisible())
                jTFBuscador.setVisible(false);
            
            modeloTablaProductos.setRowCount(0);
            modeloTablaTallas.setRowCount(0);
            btnIngresarCantidad.setVisible(false);
        }
    }//GEN-LAST:event_jCBFiltroItemStateChanged

    private void jCBCategoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCategoriaItemStateChanged
        
    }//GEN-LAST:event_jCBCategoriaItemStateChanged

    private void jTProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProductosMouseClicked
        
    }//GEN-LAST:event_jTProductosMouseClicked

    private void jTallas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTallas1MouseClicked
        if(jTallas1.getSelectedRow() != -1)
            btnIngresarCantidad.setVisible(true);
        else
            btnIngresarCantidad.setVisible(false);
    }//GEN-LAST:event_jTallas1MouseClicked

    private void activarBuscador(){
        jTFBuscador.getDocument().addDocumentListener( new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {tablaDinamica();}

            @Override
            public void removeUpdate(DocumentEvent e) {tablaDinamica();}

            @Override
            public void changedUpdate(DocumentEvent e) {tablaDinamica();}
        });
    }
    
    private void tablaDinamica(){
        campoValido = ControlOperaciones.validarCampoInvalidoTexto(jTFBuscador);
        
        btnIngresarCantidad.setEnabled(true);
    }
    
    private void filtrarBuscador(String nuevoTítulo){
        if(jLFiltroCategoria.isVisible())
            jLFiltroCategoria.setVisible(false);
        
        if(jCBCategoria.isVisible())
            jCBCategoria.setVisible(false);
        
        if(!jLBuscador.isVisible())
            jLBuscador.setVisible(true);
        
        if(!jTFBuscador.isVisible())
            jTFBuscador.setVisible(true);
        
        jLBuscador.setText(nuevoTítulo);
        jTFBuscador.setText("");
        modeloTablaProductos.setRowCount(0);
        modeloTablaTallas.setRowCount(0);
        btnIngresarCantidad.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarCantidad;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jCBCategoria;
    private javax.swing.JComboBox<String> jCBFiltro;
    private javax.swing.JLabel jLBuscador;
    private javax.swing.JLabel jLFiltroBusqueda;
    private javax.swing.JLabel jLFiltroCategoria;
    private javax.swing.JLabel jLTítuloNuevoProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFBuscador;
    private javax.swing.JTable jTProductos;
    private javax.swing.JTable jTallas;
    private javax.swing.JTable jTallas1;
    // End of variables declaration//GEN-END:variables
}