package moduloVentas;

import control.ControlOperaciones;
import dtos.DetalleVentaTallaDTO;
import dtos.StockPorTallaDTO;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author PC WHITE WOLF
 */
public class IngresarCantidad extends javax.swing.JDialog {
    
    private StockPorTallaDTO tallaVender;
    private final List<DetalleVentaTallaDTO> tallasVender;
    private boolean cantidadValida;
    private boolean estado;
    
    /**
     * Creates new form IngresarCantidad
     * @param parent
     * @param modal
     */
    public IngresarCantidad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        btnAceptar.setVisible(false);
        tallasVender = new ArrayList<>();
        estado = false;
        ControlOperaciones.configurarCamposCantidades(jTFCantidad);
        ControlOperaciones.limiteCaracteres(jTFCantidad, 20);
        validacionDinamica();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPIngresarCantidad = new javax.swing.JPanel();
        jLIngresarCantidad = new javax.swing.JLabel();
        jTFCantidad = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(600, 300));
        setMinimumSize(new java.awt.Dimension(600, 300));
        setName("IngresarCantidad"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 300));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPIngresarCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jPIngresarCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jPIngresarCantidad.setMaximumSize(new java.awt.Dimension(600, 300));
        jPIngresarCantidad.setMinimumSize(new java.awt.Dimension(600, 300));
        jPIngresarCantidad.setPreferredSize(new java.awt.Dimension(600, 300));
        jPIngresarCantidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLIngresarCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jLIngresarCantidad.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLIngresarCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jLIngresarCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIngresarCantidad.setText("Ingrese la cantidad a vender:");
        jLIngresarCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPIngresarCantidad.add(jLIngresarCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 36));

        jTFCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTFCantidad.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTFCantidad.setForeground(new java.awt.Color(0, 0, 0));
        jTFCantidad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTFCantidad.setText("0");
        jTFCantidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPIngresarCantidad.add(jTFCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 33));

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPIngresarCantidad.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 92, 39));
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setOpaque(false);
        btnCancelar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 20, 20);
                super.paint(g2, c);
                g2.dispose();
            }
        });

        btnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        btnAceptar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setFocusPainted(false);
        btnAceptar.setFocusable(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPIngresarCantidad.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 92, 39));
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setOpaque(false);
        btnAceptar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 20, 20);
                super.paint(g2, c);
                g2.dispose();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPIngresarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPIngresarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jLIngresarCantidad.setText("Ingrese la cantidad a vender");
        jTFCantidad.setText("0");
        setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        if(tallaVender != null && tallasVender != null){
            DetalleVentaTallaDTO tallaVenta = new DetalleVentaTallaDTO();
            tallaVenta.setTalla(tallaVender.getTalla());
            tallaVenta.setCantidadVendida(Integer.valueOf(jTFCantidad.getText()));
            tallasVender.add(tallaVenta);
            if(!estado)
                estado = true;
            jLIngresarCantidad.setText("Ingrese la cantidad a vender");
            jTFCantidad.setText("0");
            setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        if(tallaVender != null){
            jLIngresarCantidad.setText("Ingresar cantidad para " + tallaVender.getTalla().getTalla() + ":");
        } else{
            jLIngresarCantidad.setText("Ingrese la cantidad a vender");
            jTFCantidad.setText("0");
        }
    }//GEN-LAST:event_formComponentShown
    
    public void agregarTalla(StockPorTallaDTO talla){
        if(talla != null){
            this.tallaVender = talla;
            jLIngresarCantidad.setText("Ingresar cantidad para " + tallaVender.getTalla().getTalla() + ":");
        }
    }
    
    private void validacionDinamica(){
        jTFCantidad.getDocument().addDocumentListener( new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                validarCampo();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                validarCampo();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                validarCampo();
            }
        });
    }
    
    private void validarCampo(){
        cantidadValida = ControlOperaciones.validarCampoInvalidoCantidades(jTFCantidad) && (tallaVender.getStock() - Integer.valueOf(jTFCantidad.getText())) >= 0;
        if(cantidadValida){
            jLIngresarCantidad.setText("Ingresar cantidad para " + tallaVender.getTalla().getTalla() + ":");
            btnAceptar.setVisible(true);
        } else{
            if(!jTFCantidad.getText().isEmpty()){
                jLIngresarCantidad.setText("La cantidad ingresada supera el stock disponible de la talla " + tallaVender.getTalla().getTalla());
                btnAceptar.setVisible(false);
            } else{
                jLIngresarCantidad.setText("Por favor, ingrese una cantidad para la talla " + tallaVender.getTalla().getTalla());
                btnAceptar.setVisible(false);
            }
            
        }
    }
    
    public void setTallaVender(StockPorTallaDTO talla){this.tallaVender = talla;}
    
    public boolean getEstado(){return this.estado;}
    
    public List<DetalleVentaTallaDTO> getTallas(){return this.tallasVender;}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLIngresarCantidad;
    private javax.swing.JPanel jPIngresarCantidad;
    private javax.swing.JTextField jTFCantidad;
    // End of variables declaration//GEN-END:variables
}