package moduloVentas;

import control.ControlFlujo;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JComponent;

/**
 *
 * @author PC WHITE WOLF
 */
public class SubmenuVentas extends javax.swing.JPanel {
    
    private static SubmenuVentas instance;
    
    /**
     * Creates new form SubmenuCompras
     */
    private SubmenuVentas() {initComponents();}
    
    public static SubmenuVentas getInstance(){
        if(instance == null)
            instance = new SubmenuVentas();
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTítuloCompras = new javax.swing.JLabel();
        btnVender = new javax.swing.JLabel();
        btnHistorialVentas = new javax.swing.JLabel();
        IconoVender = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        IconoHistorialVentas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jLTítuloCompras.setText("Compras");
        jLTítuloCompras.setBackground(new java.awt.Color(255, 255, 255));
        jLTítuloCompras.setFont(new java.awt.Font("Century Gothic", 1, 72)); // NOI18N
        jLTítuloCompras.setForeground(new java.awt.Color(0, 0, 0));

        btnVender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVender.setText("Vender");
        btnVender.setBackground(new java.awt.Color(255, 255, 255));
        btnVender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVender.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnVender.setForeground(new java.awt.Color(0, 0, 0));
        btnVender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVenderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVenderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVenderMouseExited(evt);
            }
        });

        btnHistorialVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHistorialVentas.setText("Historial de Ventas");
        btnHistorialVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnHistorialVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistorialVentas.setFont(new java.awt.Font("Century Gothic", 1, 60)); // NOI18N
        btnHistorialVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnHistorialVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistorialVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHistorialVentasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistorialVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistorialVentasMouseExited(evt);
            }
        });

        IconoVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoVender.png"))); // NOI18N

        btnRegresar.setText("Regresar");
        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setFocusPainted(false);
        btnRegresar.setFocusable(false);
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        IconoHistorialVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IconoHistorialVentas.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jLTítuloCompras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IconoVender)
                    .addComponent(IconoHistorialVentas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHistorialVentas)
                    .addComponent(btnVender))
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTítuloCompras)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnVender)
                        .addGap(138, 138, 138)
                        .addComponent(btnHistorialVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IconoVender)
                        .addGap(89, 89, 89)
                        .addComponent(IconoHistorialVentas)))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setOpaque(false);
        btnRegresar.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                // Pinta un fondo redondeado
                g2.setColor(c.getBackground());
                g2.fillRoundRect(0, 0, c.getWidth(), c.getHeight(), 20, 20);
                super.paint(g2, c);
                g2.dispose();
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVenderMouseClicked
        ControlFlujo.mostrarVender(null);
    }//GEN-LAST:event_btnVenderMouseClicked

    private void btnVenderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVenderMouseEntered
        btnVender.setForeground(Color.red);
    }//GEN-LAST:event_btnVenderMouseEntered

    private void btnVenderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVenderMouseExited
        btnVender.setForeground(Color.black);
    }//GEN-LAST:event_btnVenderMouseExited

    private void btnHistorialVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentasMouseClicked
        
    }//GEN-LAST:event_btnHistorialVentasMouseClicked

    private void btnHistorialVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentasMouseEntered
        btnHistorialVentas.setForeground(Color.red);
    }//GEN-LAST:event_btnHistorialVentasMouseEntered

    private void btnHistorialVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistorialVentasMouseExited
        btnHistorialVentas.setForeground(Color.black);
    }//GEN-LAST:event_btnHistorialVentasMouseExited

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        ControlFlujo.mostrarMenuPrincipal();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoHistorialVentas;
    private javax.swing.JLabel IconoVender;
    private javax.swing.JLabel btnHistorialVentas;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel btnVender;
    private javax.swing.JLabel jLTítuloCompras;
    // End of variables declaration//GEN-END:variables
}